"""init

Revision ID: 1b5207fd3d17
Revises: 
Create Date: 2026-02-14 12:09:23.751371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5207fd3d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=30), nullable=False),
    sa.Column('cnae', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guide_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'doc_type', name='uq_guide_doc_year_month_type')
    )
    with op.batch_alter_table('guide_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_document_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_document_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_document_year'), ['year'], unique=False)

    op.create_table('payroll_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('overtime_hour_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_payroll_run_year_month')
    )
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_run_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_run_year'), ['year'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('employee_dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_dependent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_dependent_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_salary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_salary_effective_from'), ['effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_salary_employee_id'), ['employee_id'], unique=False)

    op.create_table('payroll_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('overtime_hour_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overtime_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_line_run_employee')
    )
    with op.batch_alter_table('payroll_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_line_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_line_payroll_run_id'), ['payroll_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_line_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_line_employee_id'))

    op.drop_table('payroll_line')
    with op.batch_alter_table('employee_salary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_salary_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_salary_effective_from'))

    op.drop_table('employee_salary')
    with op.batch_alter_table('employee_dependent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_dependent_employee_id'))

    op.drop_table('employee_dependent')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('payroll_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_run_year'))
        batch_op.drop_index(batch_op.f('ix_payroll_run_month'))

    op.drop_table('payroll_run')
    with op.batch_alter_table('guide_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_document_year'))
        batch_op.drop_index(batch_op.f('ix_guide_document_month'))
        batch_op.drop_index(batch_op.f('ix_guide_document_doc_type'))

    op.drop_table('guide_document')
    op.drop_table('employee')
    op.drop_table('company')
    # ### end Alembic commands ###
