"""tax tables INSS/IRRF

Revision ID: 951536343444
Revises: 1b5207fd3d17
Create Date: 2026-02-14 12:40:36.843208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951536343444'
down_revision = '1b5207fd3d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_inss_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('up_to', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_inss_bracket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_inss_bracket_effective_from'), ['effective_from'], unique=False)

    op.create_table('tax_irrf_bracket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('up_to', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_irrf_bracket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_irrf_bracket_effective_from'), ['effective_from'], unique=False)

    op.create_table('tax_irrf_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('dependent_deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_irrf_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_irrf_config_effective_from'), ['effective_from'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_irrf_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_irrf_config_effective_from'))

    op.drop_table('tax_irrf_config')
    with op.batch_alter_table('tax_irrf_bracket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_irrf_bracket_effective_from'))

    op.drop_table('tax_irrf_bracket')
    with op.batch_alter_table('tax_inss_bracket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_inss_bracket_effective_from'))

    op.drop_table('tax_inss_bracket')
    # ### end Alembic commands ###
